### ISSUE TITLE
关于搜索插件的问题

### ISSUE THREAD

**Issue by Fionn96** [Zhengqbbb/vuepress-blog#1]
大佬，使用algolia有些困难，因为不符合爬取的名单还要自己运行爬虫，对蠢萌来说过于硬核，是否考虑使用别的搜索插件？
例如[vuepress-plugin-next-search](https://www.npmjs.com/package/vuepress-plugin-next-search)

**Comment by Zhengqbbb** [comment]
https://v2-vuepress-theme-gungnir.vercel.app/zh/docs/basic/search.html


1. remove plugin:
https://github.com/Zhengqbbb/vuepress-blog/blob/9f3933f3635d0a5d9f7235bbe256e3b9dbde9d09/blog/.vuepress/config.ts#L16

```diff
plugins: [
-   pagePlugins.docSearchPlugin,
    pagePlugins.codeCopyPlugin,
    pagePlugins.searchCNConsolePlugin,
  ],
```

2. turn on search
https://github.com/Zhengqbbb/vuepress-blog/blob/9f3933f3635d0a5d9f7235bbe256e3b9dbde9d09/blog/.vuepress/configs/pageInfo/index.ts#L104
```diff
    pwa: true,
-   search: false,
  },
```
