### ISSUE TITLE
[question] Questions about the catalog function

### ISSUE THREAD

**Issue by Fionn96** [Zhengqbbb/vuepress-blog#2]
hello. how to enable the catalog function in the docs page?
![](https://s1.vika.cn/space/2022/10/25/422a0a640adb42e58a3ba65f067ebec4)
![](https://s1.vika.cn/space/2022/10/25/1c22ba4f081441438de7f06b885e2e1d)

可以使 docs 下的文档左侧边栏显示一级和二级标题, 而在右侧可以显示其余标题。

**Comment by Zhengqbbb** [comment]
1. use `@vuepress/plugin-toc`custom theme
2. fork and custom the theme.

As i know vuepress docs mode only support left sidebar show page title.

The first pic is post mode which author using [`md-plugin-toc`](https://www.npmjs.com/package/markdown-it-table-of-contents) to complete right-sidebar.
